### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by angoodkind** [lpanebr/autoNumberHeadings#15]
Is it possible to add keyboard shortcuts to the two functions?

**Comment by lpanebr** [comment]
Hi, I use the "Lord of The Rings" shortcut `Alt+/` to rule all others!

It opens the find command with focus so I can just start typing, select and press `Enter`.
![image](https://github.com/lpanebr/autoNumberHeadings/assets/129185/c44f2913-a029-4d85-bbbd-afb4587be5cc)
