### ISSUE TITLE
BUG: Comments in headings are lost

### ISSUE THREAD

**Issue by sheldrake** [lpanebr/autoNumberHeadings#16]
Thanks for this script. One small issue. When collaborating on a Gdoc, I need to leave a message at the top of the doc asking for comments to be made against normal body text only as running the script makes comments associated with headings disappear. They still seem to remain in the comment history unresolved, but you wouldn't know to look there if you didn't know what was happening.

**Comment by lpanebr** [comment]
hmmm... Loosing comments is very problematic.
Thanks for the feedback!! I'll work on a fix.
Meanwhile check the new version. It has other fixes and new features!

**Comment by lpanebr** [comment]
Hey, I just realized that the refactoring I did to add the new features also fixed this issue!

**Comment by lpanebr** [comment]
Hey, I just realized that the refactoring I did to add the new features also fixed this issue!
